---
title: "RWorksheet6"
author: "Mechelle Simpron"
date: "2022-12-03"
output: pdf_document
---
```{r, vector = TRUE}
library(dplyr)
library(ggplot2)
library(tinytex)
```

```{r 1}
data(mpg)
data_set <- glimpse(mpg)
data_set

# Answer: There are 11 columns, and 234 rows in mpg data set.

```

```{r 2}
#Which manufacturer has the most models in this data set?
most_Model <- data_set %>% group_by(manufacturer) %>% count()
most_Model
colnames(most_Model) <- c("Manufacturer","Counts")
most_Model
# The manufacturer that has most model are the Dodge that has 37 models.
```

``` {r 2.1}
#Which model has the most variations?
most_Variation<- data_set %>% group_by(model) %>% count()
most_Variation
colnames(most_Variation) <- c("Model","Counts")
most_Variation
# The model that has most variation is the Caravan 2wd model, that has 11 variations.
```

``` {r 2A}
#Group the manufacturers and find the unique models. Copy the codes and result.
model_Unique <- data_set %>% group_by(manufacturer, model) %>% distinct() %>% count()
model_Unique
colnames(model_Unique) <- c("Manufacturer", "Model","Counts")
model_Unique
```

``` {r 2B}
#Graph the result by using plot() and ggplot(). Write the codes and its result.
plot(model_Unique)
ggplot(model_Unique, aes(x = Model, y = Counts )) + geom_point(color='skyblue')
```

``` {r 3}
#Same data set will be used. You are going to show the relationship of the model and the manufacturer.
ggplot(model_Unique, aes(x = Model, y = Manufacturer )) + geom_point(color='skyblue')
```

``` {r 3A}
# What does ggplot(mpg, aes(model, manufacturer)) + geom_point() show?
ggplot(mpg, aes(model, manufacturer)) + geom_point()
# The gglpot codes displays the graph models of manufacturers with black geom points color.
```

``` {r 3B}
# For you, is it useful? If not, how could you modify the data to make it more informative?
##Yes, it is useful because it shows the detailed result of the graphs and plots.

```

``` {r 4}
# Using  pipe (%>%), group the model and get the number of cars per model. Show codes and its result.
c_Model <- data_set %>% group_by(model) %>% count()
c_Model
colnames(c_Model) <- c("Model","Counts")
c_Model
```

``` {r 4A}
#Plot using the geom_bar() + coord_flip() just like what is shown below.Show codes and its result.

qplot(model,data = mpg,main = "Number of Cars per Model", xlab = "Model",
      ylab = "Number of Cars", geom = "bar", fill = manufacturer) +
  coord_flip()
```

``` {r 4B}
# Use only the top 20 observations. Show code and results.
m <- c_Model[1:20,] %>% top_n(2)
m
```

``` {r 5A}
# Plot the relationship between cyl - number of cylinders and displ - engine displacement 
#using geom_point with aesthetic colour = engine displacement. Title should be
#“Relationship between No. of Cylinders and Engine Displacement”.

#a. Show the codes and its result.

ggplot(mpg, aes(x = displ , y = cyl, col = displ )) + geom_point()

ggplot( data = mpg) +
  geom_point(mapping = aes(x = displ , y = cyl, col = displ))

ggplot(data = mpg, mapping = aes(x = displ, y = cyl)) +
  geom_point(mapping=aes(color=displ))

```

``` {r 5B}
#  How would you describe its relationship?
##The relationship is consistent or stable
```


``` {r 6f}
#Get the total number of observations for drv - type of drive train (f = front-wheel drive, r = rear wheel drive, 4 = 4wd) and class - type of class (Example: suv, 2seater, etc.).
wheel_drive <- subset(mpg, drv == 'f')
wheel_drive <- nrow(wheel_drive)
wheel_drive
```

``` {r 6r}
rear_wheeld <- subset(mpg, drv == 'r')
nrow(rear_wheeld)
rear_wheeld
```

``` {r 64}
num4 <- subset(mpg, drv == '4')
nrow(num4)
num4
```

``` {r suv}
suv <- subset(mpg, class == 'suv')
nrow(suv)
suv
```

``` {r compact}
c <- subset(mpg, class == 'compact')
nrow(c)
c
```

``` {r midsize}
m_size <- subset(mpg, class == 'midsize')
nrow(m_size)
m_size
```

``` {r 2seater}
two_seater <- subset(mpg, class == '2seater')
nrow(two_seater)
two_seater
```

``` {r minivan}
mini_van <- subset(mpg, class == 'minivan')
nrow(mini_van)
mini_van
```

``` {r pickup}
p_u <- subset(mpg, class == 'pickup')
nrow(p_u)
p_u
```

``` {r subcompavt}
sub_comp <- subset(mpg, class == 'subcompact')
nrow(sub_comp)
sub_comp
```

``` {r 6A}
#Plot using the geom_tile() where the number of observations for class be used as a fill for aesthetics.
#a. Show the codes and its result for the narrative in #6.

ggplot(mpg, aes(drv, class)) +
  geom_tile (aes(fill = class)) 
```

``` {r 6B}
#Interpret the result.
##The result shows a tile created by the relationship between a class and drv.
```

``` {r 7}
# Discuss the difference between these codes. Its outputs for each are shown below.
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, colour = "purple"))
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), colour = "purple")

##In the first code, the "colour = blue" code was inside the function aes(), the results failed 
##to give a color blue dots or points. The second code was executed and 
##in its proper place or outside the aes() function, that result the correct plot.
```

``` {r 8A}
#Try to run the command ?mpg. What is the result of this command?
#Which variables from mpg data set are categorical?

#Categorical variables in mpg include: manufacturer, model, trans (type of transmission), drv (front-wheel drive, rear-wheel, 4wd), fi (fuel type), and class (type of car).
```

``` {r 8B}
#Which are continuous variables?

#Continuous variables in mpg include: displ (engine displacement in litres), cyl (number of cylinders), cty (city miles/gallon), and hwy (highway gallons/mile)
```

``` {r 8C}
#Plot the relationship between displ (engine displacement) and hwy(highway miles per gallon). Mapped it with a continuous variable you have identified in 
#5-b. What is its result? Why it produced such output?
ggplot( data = mpg) +
  geom_point(mapping = aes(x = displ , y = hwy, col = displ))

##The data shows that they are in the positive rate using the displ for hwy and cty scattered plot.
```

``` {r 9}
#Plot the relationship between displ (engine displacement) and hwy(highway miles per gallon) using geom_point(). Add a trend line over the existing plot using
#  geom_smooth() with se = FALSE. Default method is “loess”.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping=aes(color=displ)) +
  geom_smooth(se =FALSE)
```

``` {r 10}
#Using the relationship of displ and hwy, add a trend line over existing plot. Set the
# se = FALSE to remove the confidence interval and method = lm to check for linear modeling.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping=aes(color=displ)) +
  geom_smooth(se =FALSE,method = lm)
```




