---
title: "SIMPRON_INDIVIDUALPROJECT-2"
author: "MECHELLE SIMPRON"
date: "2022-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r download}
library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)
```

``` {r keys}
CONSUMER_SECRET <- "Mst3hKLpQWZynyjoDaxruTrq9D5GYedxHVa2Lno1r8DExrrRke"
CONSUMER_KEY <- "InbLhdO22Q9Z5EhRdRpCButTh"
ACCESS_SECRET <- "yu2OkGybfvGBw15hBoDSfSfGH7jGwyFBjooVs6iMO0Fzm"
ACCESS_TOKEN <- "1595247869958627328-jGgiCN6sMO8yDd3dk2G1gzqMQhQ77R"
```

```{r setUp}
setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)
```

```{r extract}
SEVENTEEN = searchTwitter("SEVENTEEN", n = 10000, since = "2022-12-14", until = "2022-12-17",
                          lang = "en", retryOnRateLimit = 120)
SEVENTEEN
```

```{r convert}
SEVENTEENDF <- twListToDF(SEVENTEEN)
```

```{r save}
save(SEVENTEENDF,file = "SEVENTEENDF.Rdata")
```

```{r load}
load(file = "SEVENTEENDF.Rdata")
```

```{r check}
data_checking <- sapply(SEVENTEENDF, function(x) sum(is.na(x)))
data_checking
```

```{r subset}
tweets <- SEVENTEENDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)
tweets
```

```{r group}
tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

crt_data <- tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
crt_data

mn <- tweets %>% pull(created) %>% min()
mn 
mx <- tweets %>% pull(created) %>% max()
mx
```

```{r plot}
plt_data <- ggplot(crt_data, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "green", high = "blue")

plt_data %>% ggplotly()
```

```{r subsetRt}
sub_tweets <- SEVENTEENDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == TRUE)
sub_tweets


sub_tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

crt2 <- sub_tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
crt2

mn <- sub_tweets %>% pull(created) %>% min()
mn 
mx <- sub_tweets %>% pull(created) %>% max()
mx
```

```{r plotRt}
plt_data <- ggplot(crt2, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "blue", high = "pink")

plt_data %>% ggplotly()
```
